# Generated by Django 5.2.17 on 2026-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('openapi_url', models.URLField(blank=True, max_length=1000)),
                ('base_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('failed', 'failed'), ('disabled', 'disabled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
