# Generated by Django 5.2.17 on 2026-09-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='app_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='car_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='is_ai_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='mcp_endpoint_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='mcp_health_status',
            field=models.CharField(blank=True, default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='mcp_transport_type',
            field=models.CharField(blank=True, default='Streamable HTTP', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='mcp_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='support_dl',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='swagger_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
