# Generated by Django 5.2.17 on 2026-09-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published_to_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('failed', 'failed'), ('disabled', 'disabled'), ('maintenance', 'maintenance')], default='pending', max_length=20),
        ),
    ]
