# Generated by Django 5.2.17 on 2026-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_catalog_flag_maintenance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_summary_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
