# Generated by Django 5.2.17 on 2026-09-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='answer_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='api_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='outcome',
            field=models.CharField(blank=True, choices=[('answered', 'Answered from an API call'), ('not_app_related', 'Not about the application (greeting, small talk, ...)'), ('no_match', 'No tool matched the question'), ('selection_failed', 'The LLM could not pick a tool'), ('api_error', "The tool's API call failed"), ('format_failed', 'API data came back but no answer could be written')], max_length=30),
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='tools_matched',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conversationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
