# Generated by Django 5.2.17 on 2026-09-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversationlog_answer_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='llm_formated_resp',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
