# Generated by Django 5.2.17 on 2026-09-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversationlog_field_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlog',
            name='llm_formated_resp',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
