# Generated by Django 5.2.17 on 2026-09-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('openapi_version', models.CharField(blank=True, max_length=50)),
                ('base_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='projects.project')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'APIs',
                'ordering': ['project_id', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
