# Generated by Django 5.2.17 on 2026-09-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='spec_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
