# Generated by Django 5.2.17 on 2026-09-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_registry', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('path', models.CharField(max_length=1000)),
                ('operation_id', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('request_schema', models.JSONField(blank=True, default=dict)),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('required_security_groups', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api_registry.api')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('query', 'query'), ('path', 'path'), ('body', 'body'), ('header', 'header'), ('cookie', 'cookie')], default='query', max_length=20)),
                ('data_type', models.CharField(default='string', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('enum_values', models.JSONField(blank=True, default=list)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='tools.tool')),
            ],
            options={
                'ordering': ['tool_id', '-required', 'name'],
                'unique_together': {('tool', 'name', 'location')},
            },
        ),
    ]
