# Generated by Django 5.2.17 on 2026-09-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tool',
            name='required_permission',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
