# Generated by Django 5.2.17 on 2026-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_display_name_tool_required_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='call_sequence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tool',
            name='sample_inputs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='sample_outputs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='when_not_to_use',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tool',
            name='when_to_use',
            field=models.TextField(blank=True, default=''),
        ),
    ]
